# Generated by Django 2.2.5 on 2020-01-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='technology',
            new_name='heading',
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='workhr',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
