# Generated by Django 2.2.5 on 2020-01-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogcatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogcatmodel',
            name='name2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
